// ─── Env ──────────────────────────────────────────────────────────────────
export const WORKER_URL = process.env.REACT_APP_WORKER_URL;
export const UPLOAD_SECRET = process.env.REACT_APP_UPLOAD_SECRET;

// ─── Currency ─────────────────────────────────────────────────────────────
export const ZAR_TO_USD = 16.53;

export const fmt = (n) =>
  `US$${(Number(n) / ZAR_TO_USD).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

// ─── Voucher code generator ───────────────────────────────────────────────
export const genCode = () =>
  "VCH-" +
  [...Array(8)]
    .map(
      () => "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random() * 32)],
    )
    .join("");

// ─── QR helper ────────────────────────────────────────────────────────────
export const QR_URL = (data) =>
  `https://api.qrserver.com/v1/create-qr-code/?size=160x160&color=1A2E1F&bgcolor=F5F0E8&data=${encodeURIComponent(data)}`;

// ─── Category icon map ────────────────────────────────────────────────────
export const getCatIcon = (cat) =>
  ({
    Wellness: "🧖",
    Beauty: "💅",
    Adventure: "🪂",
    "Dining & Wine": "🍷",
    Stays: "🏡",
    Skills: "📚",
    Music: "🎵",
    Events: "🎪",
    Florists: "🌸",
    "Traditional Restaurants": "🍲",
    Other: "🎁",
  })[cat] || "🎁";

// ─── Voucher templates seeded on partner registration ─────────────────────
export const VOUCHER_TEMPLATES = [
  {
    name: "60-Min Full Body Massage",
    category: "Wellness",
    price: 550,
    validMonths: 12,
    icon: "massage",
    desc: "Swedish, deep tissue or aromatherapy of choice",
  },
  {
    name: "Couples Spa Day",
    category: "Wellness",
    price: 1800,
    validMonths: 12,
    icon: "couples_spa",
    desc: "Side-by-side treatments, sparkling wine & lunch",
  },
  {
    name: "Hot Stone Therapy",
    category: "Wellness",
    price: 750,
    validMonths: 12,
    icon: "hot_stone",
    desc: "90-min volcanic hot stone full-body treatment",
  },
  {
    name: "Luxury Pamper Package",
    category: "Beauty",
    price: 480,
    validMonths: 6,
    icon: "pamper",
    desc: "Gel mani, spa pedi & eyebrow shaping",
  },
  {
    name: "Bridal Glow Package",
    category: "Beauty",
    price: 1950,
    validMonths: 12,
    icon: "bridal",
    desc: "Full bridal prep: hair, makeup, nails & skin",
  },
  {
    name: "Tandem Skydive",
    category: "Adventure",
    price: 2950,
    validMonths: 24,
    icon: "skydive",
    desc: "15,000ft freefall with certified instructor",
  },
  {
    name: "Hot Air Balloon Sunrise",
    category: "Adventure",
    price: 2400,
    validMonths: 18,
    icon: "balloon",
    desc: "Champagne breakfast flight over Magaliesberg",
  },
  {
    name: "Wine Tasting for Two",
    category: "Dining & Wine",
    price: 620,
    validMonths: 12,
    icon: "wine",
    desc: "6-wine flight with artisan cheese board",
  },
  {
    name: "Sunday Lunch for Two — Kwa Terry",
    category: "Traditional Restaurants",
    price: 420,
    validMonths: 12,
    icon: "kwa_terry",
    desc: "A proper Zimbabwean Sunday lunch for two at Kwa Terry.",
  },
  {
    name: "Family Feast — Kwa Terry (4 People)",
    category: "Traditional Restaurants",
    price: 980,
    validMonths: 12,
    icon: "kwa_terry_family",
    desc: "Treat the whole family to a hearty traditional feast at Kwa Terry.",
  },
  {
    name: "Feli Nandi's — Lunch for Two",
    category: "Traditional Restaurants",
    price: 380,
    validMonths: 12,
    icon: "feli_nandi",
    desc: "A sit-down traditional lunch at Feli Nandi's.",
  },
  {
    name: "Feli Nandi's — Mother's Special Treat",
    category: "Traditional Restaurants",
    price: 650,
    validMonths: 12,
    icon: "feli_nandi_mum",
    desc: "The ultimate long-distance gift for mum.",
  },
  {
    name: "Roadrunner Chicken Braai Lunch",
    category: "Traditional Restaurants",
    price: 320,
    validMonths: 6,
    icon: "roadrunner",
    desc: "Free-range road runner chicken braaied over open fire.",
  },
  {
    name: "Sadza & Dovi Dinner for Two",
    category: "Traditional Restaurants",
    price: 350,
    validMonths: 6,
    icon: "sadza_dovi",
    desc: "Sadza with peanut butter stew, covo greens and roasted groundnuts.",
  },
  {
    name: "Traditional Breakfast Spread",
    category: "Traditional Restaurants",
    price: 240,
    validMonths: 6,
    icon: "trad_breakfast",
    desc: "Mahewu, rapoko porridge, roasted sweet potato and fresh maputi.",
  },
  {
    name: "Whole Family Sunday Roast (Up to 6)",
    category: "Traditional Restaurants",
    price: 1450,
    validMonths: 12,
    icon: "family_roast",
    desc: "A full Sunday roast for up to 6 family members.",
  },
  {
    name: "Braai Masterclass",
    category: "Dining & Wine",
    price: 695,
    validMonths: 12,
    icon: "braai",
    desc: "Learn to braai like a pro — fire, meat & stories",
  },
  {
    name: "Shona Language Basics — 4 Session Bundle",
    category: "Skills",
    price: 850,
    validMonths: 12,
    icon: "shona_language",
    desc: "Four 1-hour beginner Shona lessons with a native speaker.",
  },
  {
    name: "Zimbabwe Business Setup Consultation",
    category: "Skills",
    price: 1200,
    validMonths: 12,
    icon: "biz_setup",
    desc: "90-minute 1-on-1 session with a local business consultant.",
  },
  {
    name: "Expat Orientation Day",
    category: "Skills",
    price: 980,
    validMonths: 12,
    icon: "expat_orientation",
    desc: "A full guided half-day for new arrivals.",
  },
  {
    name: "Zimbabwe Driving & Road Rules Crash Course",
    category: "Skills",
    price: 650,
    validMonths: 6,
    icon: "driving_lesson",
    desc: "A 2-hour practical session for foreigners.",
  },
  {
    name: "Shona Stone Sculpture Workshop",
    category: "Skills",
    price: 750,
    validMonths: 12,
    icon: "sculpture_workshop",
    desc: "A hands-on 3-hour sculpting session with a Zimbabwean master sculptor.",
  },
  {
    name: "Traditional Cooking Masterclass",
    category: "Skills",
    price: 680,
    validMonths: 12,
    icon: "cooking_class",
    desc: "Learn to cook sadza, dovi, muriwo and roasted groundnuts.",
  },
  {
    name: "Mbira Music Introduction — 3 Lessons",
    category: "Skills",
    price: 720,
    validMonths: 12,
    icon: "mbira_lessons",
    desc: "Three 45-minute beginner lessons on the mbira.",
  },
  {
    name: "Wildlife & Bush Photography Workshop",
    category: "Skills",
    price: 1450,
    validMonths: 18,
    icon: "bush_photography",
    desc: "A full-day practical photography workshop in the bush.",
  },
  {
    name: "Ecocash & Mobile Money for Expats",
    category: "Skills",
    price: 350,
    validMonths: 6,
    icon: "mobile_money",
    desc: "A 1-hour practical session covering Ecocash and mobile banking.",
  },
  {
    name: "Zimbabwe Labour Law for Foreign Employers",
    category: "Skills",
    price: 1650,
    validMonths: 12,
    icon: "labour_law",
    desc: "A 2-hour briefing with an HR specialist.",
  },
  {
    name: "Solar & Off-Grid Living Workshop",
    category: "Skills",
    price: 890,
    validMonths: 12,
    icon: "solar_workshop",
    desc: "Learn how to set up and manage solar power.",
  },
  {
    name: "Batik & Textile Art Class",
    category: "Skills",
    price: 580,
    validMonths: 12,
    icon: "batik_class",
    desc: "A 3-hour hands-on batik and fabric dyeing workshop.",
  },
  {
    name: "Birthday Bloom Bouquet",
    category: "Florists",
    price: 350,
    validMonths: 6,
    icon: "bouquet",
    desc: "A hand-arranged seasonal bouquet perfect for birthdays.",
  },
  {
    name: "Luxury Rose Arrangement",
    category: "Florists",
    price: 680,
    validMonths: 6,
    icon: "roses",
    desc: "Premium long-stem roses arranged by a master florist.",
  },
  {
    name: "Weekly Flower Subscription",
    category: "Florists",
    price: 1200,
    validMonths: 3,
    icon: "subscription",
    desc: "4 weeks of fresh seasonal flower deliveries.",
  },
  {
    name: "Wedding Centrepiece Voucher",
    category: "Florists",
    price: 2500,
    validMonths: 12,
    icon: "wedding_flowers",
    desc: "One full table centrepiece arrangement for weddings or special events.",
  },
  {
    name: "Surprise Me Seasonal Bouquet",
    category: "Florists",
    price: 450,
    validMonths: 6,
    icon: "surprise_bouquet",
    desc: "A beautiful seasonal arrangement chosen fresh on the day.",
  },
  {
    name: "Corporate Office Flowers",
    category: "Florists",
    price: 1800,
    validMonths: 12,
    icon: "corporate_flowers",
    desc: "Monthly fresh flower arrangement for reception or boardroom.",
  },
  {
    name: "Live Jazz Evening for Two",
    category: "Music",
    price: 780,
    validMonths: 12,
    icon: "jazz",
    desc: "Two tickets to an intimate live jazz performance.",
  },
  {
    name: "Private Guitar Lesson Bundle",
    category: "Music",
    price: 650,
    validMonths: 12,
    icon: "guitar",
    desc: "4 x 45-minute private guitar lessons.",
  },
  {
    name: "Studio Recording Session",
    category: "Music",
    price: 1200,
    validMonths: 12,
    icon: "studio",
    desc: "3-hour professional studio recording session.",
  },
  {
    name: "Concert Ticket Voucher",
    category: "Music",
    price: 450,
    validMonths: 6,
    icon: "concert",
    desc: "Redeemable against any single concert ticket.",
  },
  {
    name: "DJ Workshop — Beginner",
    category: "Music",
    price: 990,
    validMonths: 12,
    icon: "dj",
    desc: "Full-day intro to DJing: mixing, beatmatching, software and equipment.",
  },
  {
    name: "Corporate Function Package",
    category: "Events",
    price: 4500,
    validMonths: 12,
    icon: "corporate",
    desc: "Half-day venue hire for up to 30 guests.",
  },
  {
    name: "Birthday Celebration Bundle",
    category: "Events",
    price: 1850,
    validMonths: 12,
    icon: "birthday",
    desc: "Private venue styling, décor package, welcome drinks for up to 20 guests.",
  },
  {
    name: "Kids Party Experience",
    category: "Events",
    price: 1200,
    validMonths: 6,
    icon: "kids_party",
    desc: "2-hour fully-hosted kids party with entertainment.",
  },
  {
    name: "Wedding Anniversary Dinner",
    category: "Events",
    price: 2200,
    validMonths: 12,
    icon: "anniversary",
    desc: "Private 5-course dinner for two at a top ZIM restaurant.",
  },
  {
    name: "Festival General Access Pass",
    category: "Events",
    price: 580,
    validMonths: 6,
    icon: "festival",
    desc: "One general-access pass redeemable at any participating festival.",
  },
  {
    name: "Ancient City Lodge — 1 Night Stay",
    category: "Stays",
    price: 2800,
    validMonths: 12,
    icon: "ancient_city",
    desc: "One night for two at Ancient City Lodge, Masvingo. Breakfast included.",
    imageUrl: "/images/ancient-city-lodge-masvingo-698880.webp",
  },
  {
    name: "Great Zimbabwe Ruins Weekend",
    category: "Stays",
    price: 5200,
    validMonths: 12,
    icon: "great_zim_weekend",
    desc: "Two nights for two at Ancient City Lodge — guided ruins tour & breakfast.",
  },
  {
    name: "Masvingo Heritage Escape",
    category: "Stays",
    price: 3600,
    validMonths: 12,
    icon: "masvingo_escape",
    desc: "One night bed & breakfast plus a private guided tour of Great Zimbabwe.",
  },
];
